//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginEmpleado.CRUD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Empleado
    {
        public int EmpleadoID { get; set; }
        [Required(ErrorMessage = "Dato obligatorio.")]
        public string Rut { get; set; }
        [DisplayName("Nombre")]
        public string FirstName { get; set; }
        [DisplayName("Apellido")]
        public string LastName { get; set; }
        public string Genero { get; set; }
        [DisplayName("Nacimiento")]
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Profesion { get; set; }
        public Nullable<int> Experiencia { get; set; }
        [DisplayName("Sueldo")]
        public Nullable<int> Salario { get; set; }
        [DisplayName("Imagen")]
        public string ImagePath { get; set; }
        [NotMapped]
        public HttpPostedFileBase ImageUpload { get; set; }

        public Empleado()
        {
            ImagePath = "~/AppFiles/Images/default.png";
        }
    }
}
